name: Generate a report

on:
  schedule:
    - cron: '48 21 * * *'

jobs:
  run_report:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - run: npm i
      - run: npm run clean
      - run: npm run build
      - run: npm run report
      - run: git config user.name "wise-king-sullyman"
      - run: git config user.email "wise.king.sullyman@gmail.com"
      - run: git add .
      - run: git commit -m "Run report"
      - run: git push origin main
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - run: npm install --verbose
      - run: npm run clean
      - run: npm run build
      - run: pm2 restart car_scraper_data_api
